version: '3.8'
services:
  postgres:
    container_name: postgres-ttt
    image: postgres
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: ps
      POSTGRES_DB: ttt
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure
    ports:
      - '5432:5432'
